# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Dominate
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master", "level12"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
       python: ["3"]
       os: ["ubuntu-latest"]
       include:
          - {python: "3.9", os: "ubuntu-22.04"}
          - {python: "3.10", os: "ubuntu-22.04"}
          - {python: "3.11", os: "ubuntu-22.04"}
          - {python: "3.12", os: "ubuntu-22.04"}
          - {python: "3.13", os: "ubuntu-24.04"}
          - {python: "pypy3.10", os: "ubuntu-24.04"}
    steps:
    - uses: actions/checkout@v4

    # https://docs.astral.sh/uv/guides/integration/github/#multiple-python-versions
    - name: Install uv and Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: "Run nox"
      run: |
        uv run --only-group nox nox

    - name: Coveralls
      # Only push coverage on the project's repo (no forks) and when tests have passed
      if: github.repository == 'Knio/dominate' && success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        uv run --only-group coverage -- coveralls --service=github || true
